# Generated by Django 3.1.4 on 2020-12-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menu_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_ins', models.CharField(max_length=256, null=True)),
                ('sm_ins_icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_mail', models.CharField(max_length=256, null=True)),
                ('sm_mail_icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('footer_info', models.CharField(max_length=256, null=True)),
                ('footer_year', models.CharField(max_length=256, null=True)),
                ('footer_except', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Menu_Item',
                'verbose_name_plural': 'Menu_Items',
            },
        ),
    ]
