# Generated by Django 3.1.4 on 2020-12-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Footer_Item', 'verbose_name_plural': 'Footer_Items'},
        ),
    ]
