# Generated by Django 3.1.4 on 2020-12-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
