# Generated by Django 3.1.4 on 2020-12-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201209_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='sm_ins_icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='footer',
            name='sm_mail_icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
