# Generated by Django 3.1.4 on 2020-12-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201209_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_info',
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_about_info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
